# Data Cleaning

In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

C:\anaconda\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [3]:

df = pd.read_csv("U.S._Offense_Type_by_Agency_2012.csv")

df

,United States,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,Offense Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"by Agency, 2012",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,Agency Type,Agency Name,Population1,Total\nOffenses,Crimes\nAgainst\nPersons,Crimes\nAgainst\nProperty,Crimes\nAgainst\nSociety,Crimes Against Persons,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assault\nOffenses,Aggravated\nAssault,...,Gambling\nOffenses,Betting/\nWagering,Operating/\nPromoting/\nAssisting\nGambling,Gambling\nEquipment\nViolations,Sports\nTampering,Porno-\ngraphy/\nObscene\nMaterial,Prost-\nitution\nOffenses,Prost-\nitution,Assisting\nor Pro-\nmoting\nProst-\nitution,Weapon\nLaw\nViolations
4,ALABAMA,Cities,Hoover,"82,332","4,304",899,"2,880",525,870,25,...,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5238,NaN,NaN,St. Croix Tribal,NaN,134,14,77,43,14,1,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,11
5239,1Population figures are published only for the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5240,2This agency reported 24 Murder and Nonneglige...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5241,3Student enrollment figures were not available.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5242,4The FBI UCR Program determined this agency's ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
deleted = 1
df = df.drop(deleted)
df

KeyError: '[1] not found in axis'

In [8]:
values = df.loc[2,['United States', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']]

othervalues =  df.loc[3,['Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44',
       'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48',
       'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52',
       'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56',
       'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60','Unnamed: 61','Unnamed: 62']]

value_list = values.tolist()
other_list = othervalues.tolist()

In [9]:
value_list[4] = "Total Offenses"
value_list[5] = "Crimes Against Persons"
value_list[6] = "Crimes Against Property"
value_list[7] = "Crimes Against Society"

In [10]:
other_list

['Aggravated\nAssault',
 'Simple\nAssault',
 'Intimidation',
 'Homicide\nOffenses',
 'Murder and Nonnegligent Manslaughter',
 'Negligent\nManslaughter',
 'Justifiable\nHomicide',
 'Kidnapping/\nAbduction',
 'Sex\nOffenses',
 'Rape',
 'Sodomy',
 'Sexual\nAssault\nWith An\nObject',
 'Fondling',
 'Sex\nOffenses,\nNonforcible',
 'Incest',
 'Statutory\nRape',
 'Arson',
 'Bribery',
 'Burglary/\nBreaking &\nEntering',
 'Counter-\nfeiting/\nForgery',
 'Destruction/\nDamage/\nVandalism',
 'Embezzle-\nment',
 'Extortion/\nBlackmail',
 'Fraud\nOffenses',
 'False\nPretenses/\nSwindle/\nConfidence\nGame',
 'Credit Card/\nAutomated\nTeller\nMachine Fraud',
 'Imperson-\nation',
 'Welfare\nFraud',
 'Wire\nFraud',
 'Larceny-\nTheft\nOffenses',
 'Pocket-\npicking',
 'Purse-\nsnatching',
 'Shop-\nlifting',
 'Theft\nFrom\nBuilding',
 'Theft\nFrom\nCoin-\noperated\nMachine',
 'Theft\nFrom\nMotor\nVehicle',
 'Theft of\nMotor\nVehicle\nParts or\nAccessories',
 'All\nOther\nLarceny',
 'Motor\nVehicle\nTheft',
 'Robbery',
 'Stolen\nProperty\nOffenses ',
 'Drug/\nNarcotic\nOffenses',
 'Drug/\nNarcotic\nViolations',
 'Drug\nEquipment\nViolations',
 'Gambling\nOffenses',
 'Betting/\nWagering',
 'Operating/\nPromoting/\nAssisting\nGambling',
 'Gambling\nEquipment\nViolations',
 'Sports\nTampering',
 'Porno-\ngraphy/\nObscene\nMaterial',
 'Prost-\nitution\nOffenses',
 'Prost-\nitution',
 'Assisting\nor Pro-\nmoting\nProst-\nitution',
 'Weapon\nLaw\nViolations']

In [12]:
columns_list = value_list + other_list 
columns_list

['State',
 'Agency Type',
 'Agency Name',
 'Population1',
 'Total Offenses',
 'Crimes Against Persons',
 'Crimes Against Property',
 'Crimes Against Society',
 'Crimes Against Persons',
 'Aggravated\nAssault',
 'Simple\nAssault',
 'Intimidation',
 'Homicide\nOffenses',
 'Murder and Nonnegligent Manslaughter',
 'Negligent\nManslaughter',
 'Justifiable\nHomicide',
 'Kidnapping/\nAbduction',
 'Sex\nOffenses',
 'Rape',
 'Sodomy',
 'Sexual\nAssault\nWith An\nObject',
 'Fondling',
 'Sex\nOffenses,\nNonforcible',
 'Incest',
 'Statutory\nRape',
 'Arson',
 'Bribery',
 'Burglary/\nBreaking &\nEntering',
 'Counter-\nfeiting/\nForgery',
 'Destruction/\nDamage/\nVandalism',
 'Embezzle-\nment',
 'Extortion/\nBlackmail',
 'Fraud\nOffenses',
 'False\nPretenses/\nSwindle/\nConfidence\nGame',
 'Credit Card/\nAutomated\nTeller\nMachine Fraud',
 'Imperson-\nation',
 'Welfare\nFraud',
 'Wire\nFraud',
 'Larceny-\nTheft\nOffenses',
 'Pocket-\npicking',
 'Purse-\nsnatching',
 'Shop-\nlifting',
 'Theft\nFrom\nBuilding',
 'Theft\nFrom\nCoin-\noperated\nMachine',
 'Theft\nFrom\nMotor\nVehicle',
 'Theft of\nMotor\nVehicle\nParts or\nAccessories',
 'All\nOther\nLarceny',
 'Motor\nVehicle\nTheft',
 'Robbery',
 'Stolen\nProperty\nOffenses ',
 'Drug/\nNarcotic\nOffenses',
 'Drug/\nNarcotic\nViolations',
 'Drug\nEquipment\nViolations',
 'Gambling\nOffenses',
 'Betting/\nWagering',
 'Operating/\nPromoting/\nAssisting\nGambling',
 'Gambling\nEquipment\nViolations',
 'Sports\nTampering',
 'Porno-\ngraphy/\nObscene\nMaterial',
 'Prost-\nitution\nOffenses',
 'Prost-\nitution',
 'Assisting\nor Pro-\nmoting\nProst-\nitution',
 'Weapon\nLaw\nViolations']

In [13]:
new_list = []

for item in columns_list :
    new_list.append(item.replace('\n', ' ')) # delete \n
    
print(new_list)

df.columns = new_list

df.head(10)

['State', 'Agency Type', 'Agency Name', 'Population1', 'Total Offenses', 'Crimes Against Persons', 'Crimes Against Property', 'Crimes Against Society', 'Crimes Against Persons', 'Aggravated Assault', 'Simple Assault', 'Intimidation', 'Homicide Offenses', 'Murder and Nonnegligent Manslaughter', 'Negligent Manslaughter', 'Justifiable Homicide', 'Kidnapping/ Abduction', 'Sex Offenses', 'Rape', 'Sodomy', 'Sexual Assault With An Object', 'Fondling', 'Sex Offenses, Nonforcible', 'Incest', 'Statutory Rape', 'Arson', 'Bribery', 'Burglary/ Breaking & Entering', 'Counter- feiting/ Forgery', 'Destruction/ Damage/ Vandalism', 'Embezzle- ment', 'Extortion/ Blackmail', 'Fraud Offenses', 'False Pretenses/ Swindle/ Confidence Game', 'Credit Card/ Automated Teller Machine Fraud', 'Imperson- ation', 'Welfare Fraud', 'Wire Fraud', 'Larceny- Theft Offenses', 'Pocket- picking', 'Purse- snatching', 'Shop- lifting', 'Theft From Building', 'Theft From Coin- operated Machine', 'Theft From Motor Vehicle', 'Theft of Motor Vehicle Parts or Accessories', 'All Other Larceny', 'Motor Vehicle Theft', 'Robbery', 'Stolen Property Offenses ', 'Drug/ Narcotic Offenses', 'Drug/ Narcotic Violations', 'Drug Equipment Violations', 'Gambling Offenses', 'Betting/ Wagering', 'Operating/ Promoting/ Assisting Gambling', 'Gambling Equipment Violations', 'Sports Tampering', 'Porno- graphy/ Obscene Material', 'Prost- itution Offenses', 'Prost- itution', 'Assisting or Pro- moting Prost- itution', 'Weapon Law Violations']

,State,Agency Type,Agency Name,Population1,Total Offenses,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Aggravated Assault,...,Gambling Offenses,Betting/ Wagering,Operating/ Promoting/ Assisting Gambling,Gambling Equipment Violations,Sports Tampering,Porno- graphy/ Obscene Material,Prost- itution Offenses,Prost- itution,Assisting or Pro- moting Prost- itution,Weapon Law Violations
0,Offense Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State,Agency Type,Agency Name,Population1,Total\nOffenses,Crimes\nAgainst\nPersons,Crimes\nAgainst\nProperty,Crimes\nAgainst\nSociety,Crimes Against Persons,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assault\nOffenses,Aggravated\nAssault,...,Gambling\nOffenses,Betting/\nWagering,Operating/\nPromoting/\nAssisting\nGambling,Gambling\nEquipment\nViolations,Sports\nTampering,Porno-\ngraphy/\nObscene\nMaterial,Prost-\nitution\nOffenses,Prost-\nitution,Assisting\nor Pro-\nmoting\nProst-\nitution,Weapon\nLaw\nViolations
4,ALABAMA,Cities,Hoover,"82,332","4,304",899,"2,880",525,870,25,...,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,26
5,ARIZONA,Cities,Apache Junction,"36,986","2,693",611,"1,748",334,559,96,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,25
6,NaN,NaN,Gilbert,"214,264","10,166","1,396","6,610","2,160","1,242",123,...,NaN,NaN,NaN,NaN,NaN,16,NaN,NaN,NaN,75
7,NaN,Metropolitan Counties,Yuma2,NaN,"3,035",661,"1,890",484,555,94,...,NaN,NaN,NaN,NaN,NaN,5,2,1,1,40
8,ARKANSAS,Cities,Alma,"5,439",780,202,507,71,197,11,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,4
9,NaN,NaN,Arkadelphia,"10,698",951,290,609,52,274,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
10,NaN,NaN,Ashdown,"4,680",333,79,220,34,72,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [18]:
data = df.copy()

data.drop(data.tail(4).index,inplace=True)

In [19]:
data.shape

(5237, 63)

In [21]:
data = data.drop([0, 1]) # delete 0 and 1 indexes
data = data.reset_index(drop=True)

data

,State,Agency Type,Agency Name,Population1,Total Offenses,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Aggravated Assault,...,Gambling Offenses,Betting/ Wagering,Operating/ Promoting/ Assisting Gambling,Gambling Equipment Violations,Sports Tampering,Porno- graphy/ Obscene Material,Prost- itution Offenses,Prost- itution,Assisting or Pro- moting Prost- itution,Weapon Law Violations
0,ALABAMA,Cities,Hoover,"82,332","4,304",899,"2,880",525,870,25,...,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,26
1,ARIZONA,Cities,Apache Junction,"36,986","2,693",611,"1,748",334,559,96,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,25
2,NaN,NaN,Gilbert,"214,264","10,166","1,396","6,610","2,160","1,242",123,...,NaN,NaN,NaN,NaN,NaN,16,NaN,NaN,NaN,75
3,NaN,Metropolitan Counties,Yuma2,NaN,"3,035",661,"1,890",484,555,94,...,NaN,NaN,NaN,NaN,NaN,5,2,1,1,40
4,ARKANSAS,Cities,Alma,"5,439",780,202,507,71,197,11,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,NaN,NaN,Sauk,NaN,"1,265",134,925,206,80,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
5231,NaN,NaN,Sawyer,NaN,750,88,589,73,79,21,...,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,15
5232,NaN,NaN,Vilas,NaN,374,55,257,62,42,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
5233,NaN,Other Agencies - Tribal,Oneida Tribal,NaN,350,64,191,95,56,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
5234,NaN,NaN,St. Croix Tribal,NaN,134,14,77,43,14,1,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,11

In [23]:
data.drop(["Agency Type"], axis = 1 )

,State,Agency Name,Population1,Total Offenses,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Aggravated Assault,Simple Assault,...,Gambling Offenses,Betting/ Wagering,Operating/ Promoting/ Assisting Gambling,Gambling Equipment Violations,Sports Tampering,Porno- graphy/ Obscene Material,Prost- itution Offenses,Prost- itution,Assisting or Pro- moting Prost- itution,Weapon Law Violations
0,ALABAMA,Hoover,"82,332","4,304",899,"2,880",525,870,25,594,...,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,26
1,ARIZONA,Apache Junction,"36,986","2,693",611,"1,748",334,559,96,381,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,25
2,NaN,Gilbert,"214,264","10,166","1,396","6,610","2,160","1,242",123,892,...,NaN,NaN,NaN,NaN,NaN,16,NaN,NaN,NaN,75
3,NaN,Yuma2,NaN,"3,035",661,"1,890",484,555,94,376,...,NaN,NaN,NaN,NaN,NaN,5,2,1,1,40
4,ARKANSAS,Alma,"5,439",780,202,507,71,197,11,108,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,NaN,Sauk,NaN,"1,265",134,925,206,80,14,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
5231,NaN,Sawyer,NaN,750,88,589,73,79,21,56,...,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,15
5232,NaN,Vilas,NaN,374,55,257,62,42,3,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
5233,NaN,Oneida Tribal,NaN,350,64,191,95,56,14,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
5234,NaN,St. Croix Tribal,NaN,134,14,77,43,14,1,10,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,11

In [24]:
data.rename(columns={"Agency Name": "City"}, inplace=True)

In [31]:
data[['State', 'Agency Type']] = data[['State', 'Agency Type']].fillna(method='ffill') # fill the empty states and citys

data

,State,Agency Type,City,Population1,Total Offenses,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Aggravated Assault,...,Gambling Offenses,Betting/ Wagering,Operating/ Promoting/ Assisting Gambling,Gambling Equipment Violations,Sports Tampering,Porno- graphy/ Obscene Material,Prost- itution Offenses,Prost- itution,Assisting or Pro- moting Prost- itution,Weapon Law Violations
0,ALABAMA,Cities,Hoover,"82,332","4,304",899,"2,880",525,870,25,...,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,26
1,ARIZONA,Cities,Apache Junction,"36,986","2,693",611,"1,748",334,559,96,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,25
2,ARIZONA,Cities,Gilbert,"214,264","10,166","1,396","6,610","2,160","1,242",123,...,NaN,NaN,NaN,NaN,NaN,16,NaN,NaN,NaN,75
3,ARIZONA,Metropolitan Counties,Yuma2,NaN,"3,035",661,"1,890",484,555,94,...,NaN,NaN,NaN,NaN,NaN,5,2,1,1,40
4,ARKANSAS,Cities,Alma,"5,439",780,202,507,71,197,11,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,WISCONSIN,Nonmetropolitan Counties,Sauk,NaN,"1,265",134,925,206,80,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
5231,WISCONSIN,Nonmetropolitan Counties,Sawyer,NaN,750,88,589,73,79,21,...,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,15
5232,WISCONSIN,Nonmetropolitan Counties,Vilas,NaN,374,55,257,62,42,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
5233,WISCONSIN,Other Agencies - Tribal,Oneida Tribal,NaN,350,64,191,95,56,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
5234,WISCONSIN,Other Agencies - Tribal,St. Croix Tribal,NaN,134,14,77,43,14,1,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,11

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5235 entries, 0 to 5234
Data columns (total 63 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   State                                        5235 non-null   object
 1   Agency Type                                  5235 non-null   object
 2   City                                         5235 non-null   object
 3   Population1                                  3397 non-null   object
 4   Total Offenses                               5208 non-null   object
 5   Crimes Against Persons                       5208 non-null   object
 6   Crimes Against Property                      5208 non-null   object
 7   Crimes Against Society                       5208 non-null   object
 8   Crimes Against Persons                       4773 non-null   object
 9   Aggravated Assault                           4079 non-null   object
 10  Simple Assault                               4647 non-null   object
 11  Intimidation                                 3971 non-null   object
 12  Homicide Offenses                            937 non-null    object
 13  Murder and Nonnegligent Manslaughter         855 non-null    object
 14  Negligent Manslaughter                       149 non-null    object
 15  Justifiable Homicide                         79 non-null     object
 16  Kidnapping/ Abduction                        2004 non-null   object
 17  Sex Offenses                                 3643 non-null   object
 18  Rape                                         2843 non-null   object
 19  Sodomy                                       1519 non-null   object
 20  Sexual Assault With An Object                835 non-null    object
 21  Fondling                                     2949 non-null   object
 22  Sex Offenses, Nonforcible                    1584 non-null   object
 23  Incest                                       519 non-null    object
 24  Statutory Rape                               1414 non-null   object
 25  Arson                                        2344 non-null   object
 26  Bribery                                      195 non-null    object
 27  Burglary/ Breaking & Entering                4554 non-null   object
 28  Counter- feiting/ Forgery                    3626 non-null   object
 29  Destruction/ Damage/ Vandalism               4701 non-null   object
 30  Embezzle- ment                               1872 non-null   object
 31  Extortion/ Blackmail                         488 non-null    object
 32  Fraud Offenses                               4265 non-null   object
 33  False Pretenses/ Swindle/ Confidence Game    3566 non-null   object
 34  Credit Card/ Automated Teller Machine Fraud  3392 non-null   object
 35  Imperson- ation                              3015 non-null   object
 36  Welfare Fraud                                288 non-null    object
 37  Wire Fraud                                   1069 non-null   object
 38  Larceny- Theft Offenses                      4854 non-null   object
 39  Pocket- picking                              1044 non-null   object
 40  Purse- snatching                             1218 non-null   object
 41  Shop- lifting                                3446 non-null   object
 42  Theft From Building                          4110 non-null   object
 43  Theft From Coin- operated Machine            1099 non-null   object
 44  Theft From Motor Vehicle                     4253 non-null   object
 45  Theft of Motor Vehicle Parts or Accessories  3105 non-null   object
 46  All Other Larceny                            4707 non-null   object
 47  Motor Vehicle Theft                          4002 non-null   object
 48  Robbery                                      2411 non-null   object
 49  Stolen Property Offenses                     2961 non-null   object
 50  Drug/ Narcotic Offenses                      4753 non-null   object
 51  Drug/ Narcotic Violations                    4725 non-null   object
 52  Drug Equipment Violations                    3551 non-null   object
 53  Gambling Offenses                            219 non-null    object
 54  Betting/ Wagering                            75 non-null     object
 55  Operating/ Promoting/ Assisting Gambling     132 non-null    object
 56  Gambling Equipment Violations                78 non-null     object
 57  Sports Tampering                             3 non-null      object
 58  Porno- graphy/ Obscene Material              1601 non-null   object
 59  Prost- itution Offenses                      725 non-null    object
 60  Prost- itution                               587 non-null    object
 61  Assisting or Pro- moting Prost- itution      349 non-null    object
 62  Weapon Law Violations                        3690 non-null   object
dtypes: object(63)
memory usage: 2.5+ MB

In [45]:
drop_list = []

# For loop to calculate the percentage of null values in all columns
for column in data.columns:
    total_null = (data[column].isna().sum()) / len(data) * 100
    print(column + ': ' + '%' + str(total_null))
    
    if (total_null > 70).any():
        drop_list.append(column)

# Now 'drop_list' contains the names of columns with more than 70% null values
print("Columns to drop:", drop_list)

State: %0.0
Agency Type: %0.0
City: %0.0
Population1: %35.1098376313276
Total Offenses: %0.0
Crimes Against Persons: %Crimes Against Persons    0.515759
Crimes Against Persons    8.825215
dtype: float64
Crimes Against Property: %0.5157593123209169
Crimes Against Society: %0.5157593123209169
Crimes Against Persons: %Crimes Against Persons    0.515759
Crimes Against Persons    8.825215
dtype: float64
Aggravated Assault: %22.082139446036294
Simple Assault: %11.232091690544413
Intimidation: %24.14517669531996
Homicide Offenses: %82.10124164278892
Murder and Nonnegligent Manslaughter: %83.66762177650429
Negligent Manslaughter: %97.15377268385865
Justifiable Homicide: %98.49092645654251
Kidnapping/ Abduction: %61.7191977077364
Sex Offenses: %30.410697230181473
Rape: %45.69245463228271
Sodomy: %70.98376313276027
Sexual Assault With An Object: %84.04966571155683
Fondling: %43.6676217765043
Sex Offenses, Nonforcible: %69.74212034383955
Incest: %90.08595988538683
Statutory Rape: %72.98949379178606
Arson: %55.22445081184336
Bribery: %96.27507163323781
Burglary/ Breaking & Entering: %13.008595988538682
Counter- feiting/ Forgery: %30.73543457497612
Destruction/ Damage/ Vandalism: %10.200573065902578
Embezzle- ment: %64.2406876790831
Extortion/ Blackmail: %90.67812798471823
Fraud Offenses: %18.529130850047757
False Pretenses/ Swindle/ Confidence Game: %31.881566380133712
Credit Card/ Automated Teller Machine Fraud: %35.205348615090735
Imperson- ation: %42.40687679083094
Welfare Fraud: %94.49856733524355
Wire Fraud: %79.57975167144221
Larceny- Theft Offenses: %7.277936962750717
Pocket- picking: %80.05730659025788
Purse- snatching: %76.73352435530086
Shop- lifting: %34.1738299904489
Theft From Building: %21.48997134670487
Theft From Coin- operated Machine: %79.00668576886342
Theft From Motor Vehicle: %18.758357211079275
Theft of Motor Vehicle Parts or Accessories: %40.68767908309456
All Other Larceny: %10.085959885386819
Motor Vehicle Theft: %23.55300859598854
Robbery: %53.94460362941739
Stolen Property Offenses : %43.43839541547278
Drug/ Narcotic Offenses: %9.207258834765998
Drug/ Narcotic Violations: %9.742120343839542
Drug Equipment Violations: %32.168099331423115
Gambling Offenses: %95.81661891117479
Betting/ Wagering: %98.56733524355302
Operating/ Promoting/ Assisting Gambling: %97.4785100286533
Gambling Equipment Violations: %98.51002865329514
Sports Tampering: %99.94269340974212
Porno- graphy/ Obscene Material: %69.41738299904489
Prost- itution Offenses: %86.15090735434575
Prost- itution: %88.78701050620822
Assisting or Pro- moting Prost- itution: %93.33333333333333
Weapon Law Violations: %29.512893982808023
Columns to drop: ['Homicide Offenses', 'Murder and Nonnegligent Manslaughter', 'Negligent Manslaughter', 'Justifiable Homicide', 'Sodomy', 'Sexual Assault With An Object', 'Incest', 'Statutory Rape', 'Bribery', 'Extortion/ Blackmail', 'Welfare Fraud', 'Wire Fraud', 'Pocket- picking', 'Purse- snatching', 'Theft From Coin- operated Machine', 'Gambling Offenses', 'Betting/ Wagering', 'Operating/ Promoting/ Assisting Gambling', 'Gambling Equipment Violations', 'Sports Tampering', 'Prost- itution Offenses', 'Prost- itution', 'Assisting or Pro- moting Prost- itution']

In [46]:
for drop_column in drop_list:
    
    data.drop(drop_column, inplace=True, axis=1)
   
data.head()

,State,Agency Type,City,Population1,Total Offenses,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Aggravated Assault,...,Theft of Motor Vehicle Parts or Accessories,All Other Larceny,Motor Vehicle Theft,Robbery,Stolen Property Offenses,Drug/ Narcotic Offenses,Drug/ Narcotic Violations,Drug Equipment Violations,Porno- graphy/ Obscene Material,Weapon Law Violations
0,ALABAMA,Cities,Hoover,"82,332",0.0,899,"2,880",525,870,25,...,127,197,88,46,29,495,339,156,4,26
1,ARIZONA,Cities,Apache Junction,"36,986",0.0,611,"1,748",334,559,96,...,52,415,68,21,28,308,152,156,1,25
2,ARIZONA,Cities,Gilbert,"214,264",0.0,"1,396","6,610","2,160","1,242",123,...,35,"1,053",171,59,100,"2,069",979,"1,090",16,75
3,ARIZONA,Metropolitan Counties,Yuma2,NaN,0.0,661,"1,890",484,555,94,...,4,596,75,10,24,437,208,229,5,40
4,ARKANSAS,Cities,Alma,"5,439",0.0,202,507,71,197,11,...,NaN,126,7,1,9,66,44,22,1,4

In [58]:
deleted = ["Total Offenses"]
data = data.drop(columns = deleted)
data

,State,Agency Type,City,Population1,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Aggravated Assault,Simple Assault,...,Theft of Motor Vehicle Parts or Accessories,All Other Larceny,Motor Vehicle Theft,Robbery,Stolen Property Offenses,Drug/ Narcotic Offenses,Drug/ Narcotic Violations,Drug Equipment Violations,Porno- graphy/ Obscene Material,Weapon Law Violations
0,ALABAMA,Cities,Hoover,"82,332",899,"2,880",525,870,25,594,...,127,197,88,46,29,495,339,156,4,26
1,ARIZONA,Cities,Apache Junction,"36,986",611,"1,748",334,559,96,381,...,52,415,68,21,28,308,152,156,1,25
2,ARIZONA,Cities,Gilbert,"214,264","1,396","6,610","2,160","1,242",123,892,...,35,"1,053",171,59,100,"2,069",979,"1,090",16,75
3,ARIZONA,Metropolitan Counties,Yuma2,NaN,661,"1,890",484,555,94,376,...,4,596,75,10,24,437,208,229,5,40
4,ARKANSAS,Cities,Alma,"5,439",202,507,71,197,11,108,...,NaN,126,7,1,9,66,44,22,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,WISCONSIN,Nonmetropolitan Counties,Sauk,NaN,134,925,206,80,14,63,...,8,237,25,2,4,196,95,101,NaN,10
5231,WISCONSIN,Nonmetropolitan Counties,Sawyer,NaN,88,589,73,79,21,56,...,8,100,11,1,2,55,32,23,3,15
5232,WISCONSIN,Nonmetropolitan Counties,Vilas,NaN,55,257,62,42,3,39,...,1,94,6,1,NaN,49,49,NaN,NaN,13
5233,WISCONSIN,Other Agencies - Tribal,Oneida Tribal,NaN,64,191,95,56,14,39,...,1,44,5,NaN,NaN,92,57,35,NaN,3
5234,WISCONSIN,Other Agencies - Tribal,St. Croix Tribal,NaN,14,77,43,14,1,10,...,1,21,5,NaN,NaN,31,19,12,1,11

In [60]:
# columns that will be deleted

to_delete = ['Drug Equipment Violations','Porno- graphy/ Obscene Material',
            'Theft of Motor Vehicle Parts or Accessories', 'All Other Larceny',
            'Drug/ Narcotic Offenses','Theft From Motor Vehicle', 'Larceny- Theft Offenses',
             'Shop- lifting','Imperson- ation','Embezzle- ment', 'False Pretenses/ Swindle/ Confidence Game',
            'Counter- feiting/ Forgery','Arson','Rape','Fondling','Intimidation','Aggravated Assault', 'Simple Assault']

data = data.drop(columns = to_delete)

data.head()

,State,Agency Type,City,Population1,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Kidnapping/ Abduction,Sex Offenses,...,Burglary/ Breaking & Entering,Destruction/ Damage/ Vandalism,Fraud Offenses,Credit Card/ Automated Teller Machine Fraud,Theft From Building,Motor Vehicle Theft,Robbery,Stolen Property Offenses,Drug/ Narcotic Violations,Weapon Law Violations
0,ALABAMA,Cities,Hoover,"82,332",899,"2,880",525,870,2,25,...,391,280,202,109,410,88,46,29,339,26
1,ARIZONA,Cities,Apache Junction,"36,986",611,"1,748",334,559,14,35,...,237,447,162,62,12,68,21,28,152,25
2,ARIZONA,Cities,Gilbert,"214,264","1,396","6,610","2,160","1,242",54,79,...,728,"2,303",486,150,96,171,59,100,979,75
3,ARIZONA,Metropolitan Counties,Yuma2,NaN,661,"1,890",484,555,17,39,...,363,542,192,48,NaN,75,10,24,208,40
4,ARKANSAS,Cities,Alma,"5,439",202,507,71,197,1,4,...,99,97,13,10,39,7,1,9,44,4

In [68]:
data.columns

Index(['State', 'Agency Type', 'City', 'Population1', 'Crimes Against Persons',
       'Crimes Against Property', 'Crimes Against Society',
       'Crimes Against Persons', 'Kidnapping/ Abduction', 'Sex Offenses',
       'Sex Offenses, Nonforcible', 'Burglary/ Breaking & Entering',
       'Destruction/ Damage/ Vandalism', 'Fraud Offenses',
       'Credit Card/ Automated Teller Machine Fraud', 'Theft From Building',
       'Motor Vehicle Theft', 'Robbery', 'Stolen Property Offenses ',
       'Drug/ Narcotic Violations', 'Weapon Law Violations'],
      dtype='object')

In [82]:
columns_to_process = ['Population1', 'Crimes Against Persons', 'Crimes Against Property', 'Crimes Against Society',
                      'Kidnapping/ Abduction', 'Sex Offenses', 'Sex Offenses, Nonforcible',
                      'Burglary/ Breaking & Entering', 'Destruction/ Damage/ Vandalism', 'Fraud Offenses',
                      'Credit Card/ Automated Teller Machine Fraud', 'Theft From Building', 'Motor Vehicle Theft',
                      'Robbery', 'Stolen Property Offenses ', 'Drug/ Narcotic Violations', 'Weapon Law Violations']


for column in columns_to_process:
    # Use a lambda function to conditionally convert values to integers
    data[column] = data[column].apply(lambda x: int(x.replace(',', '')) if isinstance(x, str) else x)

    
data

,State,Agency Type,City,Population1,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Kidnapping/ Abduction,Sex Offenses,...,Burglary/ Breaking & Entering,Destruction/ Damage/ Vandalism,Fraud Offenses,Credit Card/ Automated Teller Machine Fraud,Theft From Building,Motor Vehicle Theft,Robbery,Stolen Property Offenses,Drug/ Narcotic Violations,Weapon Law Violations
0,ALABAMA,Cities,Hoover,82332.0,899,2880.0,525.0,870,2.0,25.0,...,391.0,280.0,202.0,109.0,410.0,88.0,46.0,29.0,339.0,26.0
1,ARIZONA,Cities,Apache Junction,36986.0,611,1748.0,334.0,559,14.0,35.0,...,237.0,447.0,162.0,62.0,12.0,68.0,21.0,28.0,152.0,25.0
2,ARIZONA,Cities,Gilbert,214264.0,"1,396",6610.0,2160.0,"1,242",54.0,79.0,...,728.0,2303.0,486.0,150.0,96.0,171.0,59.0,100.0,979.0,75.0
3,ARIZONA,Metropolitan Counties,Yuma2,NaN,661,1890.0,484.0,555,17.0,39.0,...,363.0,542.0,192.0,48.0,NaN,75.0,10.0,24.0,208.0,40.0
4,ARKANSAS,Cities,Alma,5439.0,202,507.0,71.0,197,1.0,4.0,...,99.0,97.0,13.0,10.0,39.0,7.0,1.0,9.0,44.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,WISCONSIN,Nonmetropolitan Counties,Sauk,NaN,134,925.0,206.0,80,3.0,37.0,...,117.0,283.0,76.0,20.0,110.0,25.0,2.0,4.0,95.0,10.0
5231,WISCONSIN,Nonmetropolitan Counties,Sawyer,NaN,88,589.0,73.0,79,NaN,6.0,...,152.0,208.0,32.0,12.0,29.0,11.0,1.0,2.0,32.0,15.0
5232,WISCONSIN,Nonmetropolitan Counties,Vilas,NaN,55,257.0,62.0,42,NaN,6.0,...,52.0,68.0,24.0,5.0,NaN,6.0,1.0,NaN,49.0,13.0
5233,WISCONSIN,Other Agencies - Tribal,Oneida Tribal,NaN,64,191.0,95.0,56,1.0,4.0,...,26.0,74.0,5.0,3.0,12.0,5.0,NaN,NaN,57.0,3.0
5234,WISCONSIN,Other Agencies - Tribal,St. Croix Tribal,NaN,14,77.0,43.0,14,NaN,NaN,...,9.0,26.0,2.0,1.0,10.0,5.0,NaN,NaN,19.0,11.0

In [91]:
pa_li = ['Population1', 'Crimes Against Persons',
       'Crimes Against Property', 'Crimes Against Society',
       'Crimes Against Persons', 'Kidnapping/ Abduction', 'Sex Offenses',
       'Sex Offenses, Nonforcible', 'Burglary/ Breaking & Entering',
       'Destruction/ Damage/ Vandalism', 'Fraud Offenses',
       'Credit Card/ Automated Teller Machine Fraud', 'Theft From Building',
       'Motor Vehicle Theft', 'Robbery', 'Stolen Property Offenses ',
       'Drug/ Narcotic Violations', 'Weapon Law Violations']


# Calculate the median for each column in 'pa_li'

for pa in pa_li:
    valid_columns = data.select_dtypes(include=[int, float]).columns
    if pa in valid_columns:
        pa_median = data[pa].median()
        data[pa] = data[pa].fillna(pa_median).copy()


# fill the empty cells with median

,State,Agency Type,City,Population1,Crimes Against Persons,Crimes Against Property,Crimes Against Society,Crimes Against Persons,Kidnapping/ Abduction,Sex Offenses,...,Burglary/ Breaking & Entering,Destruction/ Damage/ Vandalism,Fraud Offenses,Credit Card/ Automated Teller Machine Fraud,Theft From Building,Motor Vehicle Theft,Robbery,Stolen Property Offenses,Drug/ Narcotic Violations,Weapon Law Violations
0,ALABAMA,Cities,Hoover,82332.0,899,2880.0,525.0,870,2.0,25.0,...,391.0,280.0,202.0,109.0,410.0,88.0,46.0,29.0,339.0,26.0
1,ARIZONA,Cities,Apache Junction,36986.0,611,1748.0,334.0,559,14.0,35.0,...,237.0,447.0,162.0,62.0,12.0,68.0,21.0,28.0,152.0,25.0
2,ARIZONA,Cities,Gilbert,214264.0,"1,396",6610.0,2160.0,"1,242",54.0,79.0,...,728.0,2303.0,486.0,150.0,96.0,171.0,59.0,100.0,979.0,75.0
3,ARIZONA,Metropolitan Counties,Yuma2,5227.0,661,1890.0,484.0,555,17.0,39.0,...,363.0,542.0,192.0,48.0,13.0,75.0,10.0,24.0,208.0,40.0
4,ARKANSAS,Cities,Alma,5439.0,202,507.0,71.0,197,1.0,4.0,...,99.0,97.0,13.0,10.0,39.0,7.0,1.0,9.0,44.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,WISCONSIN,Nonmetropolitan Counties,Sauk,5227.0,134,925.0,206.0,80,3.0,37.0,...,117.0,283.0,76.0,20.0,110.0,25.0,2.0,4.0,95.0,10.0
5231,WISCONSIN,Nonmetropolitan Counties,Sawyer,5227.0,88,589.0,73.0,79,2.0,6.0,...,152.0,208.0,32.0,12.0,29.0,11.0,1.0,2.0,32.0,15.0
5232,WISCONSIN,Nonmetropolitan Counties,Vilas,5227.0,55,257.0,62.0,42,2.0,6.0,...,52.0,68.0,24.0,5.0,13.0,6.0,1.0,3.0,49.0,13.0
5233,WISCONSIN,Other Agencies - Tribal,Oneida Tribal,5227.0,64,191.0,95.0,56,1.0,4.0,...,26.0,74.0,5.0,3.0,12.0,5.0,3.0,3.0,57.0,3.0
5234,WISCONSIN,Other Agencies - Tribal,St. Croix Tribal,5227.0,14,77.0,43.0,14,2.0,6.0,...,9.0,26.0,2.0,1.0,10.0,5.0,3.0,3.0,19.0,11.0

In [93]:
data.to_csv("cleaned_dataset.csv")